<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <NoWarn>1591</NoWarn>
    <AssemblyName>ClientRelationshipManagement.Web</AssemblyName>
    <RootNamespace>ClientRelationshipManagement.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="cCoder.CodeAnalysis" Version="2026.8.4.2107" />
    <PackageReference Include="cCoder.Security" Version="2026.8.4.2118" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\cCoder.ClientRelationshipManagement\cCoder.ClientRelationshipManagement.csproj" />
  </ItemGroup>

</Project>
