// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cCoder.ClientRelationshipManagement.Data;

#nullable disable

namespace cCoder.ClientRelationshipManagement.Data.Migrations
{
    [DbContext(typeof(ClientRelationshipManagementDbContext))]
    [Migration("20260618081237_AddClientProcessAutomation")]
    partial class AddClientProcessAutomation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Line1")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Line2")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PoBox")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TownOrCity")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ZipOrPostalCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountOwner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("FitScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("InitialRoute")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LeadSource")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NextAction")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("NextActionDueOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OpportunitySummary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PreferredOpeningAngle")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Clients", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActivityOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClientContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientOpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NextAction")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("NextActionDueOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Outcome")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityOn");

                    b.HasIndex("ClientContactId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientMaterialId");

                    b.HasIndex("ClientOpportunityId");

                    b.ToTable("ClientActivities", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Position")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RelationshipRoute")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmailAddress");

                    b.ToTable("ClientContacts", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientHandoffPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgreedScope")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientOpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommercialTermsSummary")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("HandedOffOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("KnownRisks")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LegalEntity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OnboardingOwner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PrimaryCommercialContact")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PrimaryOperationalContact")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PrimaryTechnicalContact")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PromisedOutcomes")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedContractPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientOpportunityId");

                    b.ToTable("ClientHandoffPacks", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("SentOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SentToContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SentToContactId");

                    b.ToTable("ClientMaterials", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecisionProcess")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal?>("EstimatedAnnualValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NextAction")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("NextActionDueOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PainSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("PrimaryContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Probability")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ValueHypothesis")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PrimaryContactId");

                    b.ToTable("ClientOpportunities", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDefault");

                    b.ToTable("ClientProcessDefinitions", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientProcessDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletionOutcomeKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CurrentClientProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentClientProcessTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StartedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientProcessDefinitionId");

                    b.HasIndex("CurrentClientProcessStepId");

                    b.HasIndex("CurrentClientProcessTaskId");

                    b.HasIndex("ClientId", "State");

                    b.ToTable("ClientProcessInstances", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CallScriptTemplate")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientProcessDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DueAfterDays")
                        .HasColumnType("int");

                    b.Property<int>("DueAfterHours")
                        .HasColumnType("int");

                    b.Property<string>("EmailBodyTemplate")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSubjectTemplate")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntryPoint")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("QuestionSetTemplate")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("StageOnActivate")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StatusOnActivate")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaskInstructionsTemplate")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskTitleTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ClientProcessDefinitionId");

                    b.HasIndex("ClientProcessDefinitionId", "Sequence");

                    b.ToTable("ClientProcessSteps", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientProcessInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletionOutcomeKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DueOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("EmailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RenderedCallScript")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedEmailBody")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedEmailSubject")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RenderedInstructions")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedQuestionSet")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientProcessInstanceId");

                    b.HasIndex("ClientProcessStepId");

                    b.HasIndex("DueOn");

                    b.HasIndex("EmailId")
                        .IsUnique()
                        .HasFilter("[EmailId] IS NOT NULL");

                    b.HasIndex("State");

                    b.ToTable("ClientProcessTasks", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDefaultOutcome")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("NextClientProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OutcomeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OutcomeLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TerminalStage")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TerminalStatus")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientProcessStepId");

                    b.HasIndex("NextClientProcessStepId");

                    b.ToTable("ClientProcessTransitions", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContactEmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ContactPhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LegalEntityName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("RegisteredAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegisteredOfficeText")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("TradingName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("CompanyNumber");

                    b.HasIndex("RegisteredAddressId");

                    b.ToTable("Companies", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ApprovedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("BccAddresses")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcAddresses")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FromDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FromEmailAddress")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsBodyHtml")
                        .HasColumnType("bit");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("LastSendAttemptOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReplyToAddresses")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("ScheduledSendTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SendFailureCount")
                        .HasColumnType("int");

                    b.Property<string>("SenderUserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("SentOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SentToContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ToAddresses")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientMaterialId")
                        .IsUnique()
                        .HasFilter("[ClientMaterialId] IS NOT NULL");

                    b.HasIndex("ScheduledSendTimeUtc");

                    b.HasIndex("SentToContactId");

                    b.HasIndex("State");

                    b.ToTable("Emails", "CRM");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientActivity", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientContact", "ClientContact")
                        .WithMany("Activities")
                        .HasForeignKey("ClientContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Client", "Client")
                        .WithMany("Activities")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientMaterial", "ClientMaterial")
                        .WithMany("Activities")
                        .HasForeignKey("ClientMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientOpportunity", "ClientOpportunity")
                        .WithMany("Activities")
                        .HasForeignKey("ClientOpportunityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("ClientContact");

                    b.Navigation("ClientMaterial");

                    b.Navigation("ClientOpportunity");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientContact", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientHandoffPack", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Client", "Client")
                        .WithMany("HandoffPacks")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientOpportunity", "ClientOpportunity")
                        .WithMany("HandoffPacks")
                        .HasForeignKey("ClientOpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ClientOpportunity");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientMaterial", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Client", "Client")
                        .WithMany("Materials")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientContact", "SentToContact")
                        .WithMany()
                        .HasForeignKey("SentToContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("SentToContact");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientOpportunity", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Client", "Client")
                        .WithMany("Opportunities")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientContact", "PrimaryContact")
                        .WithMany()
                        .HasForeignKey("PrimaryContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("PrimaryContact");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessInstance", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Client", "Client")
                        .WithMany("ProcessInstances")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessDefinition", "ClientProcessDefinition")
                        .WithMany("Instances")
                        .HasForeignKey("ClientProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessStep", "CurrentClientProcessStep")
                        .WithMany("CurrentInstances")
                        .HasForeignKey("CurrentClientProcessStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessTask", "CurrentClientProcessTask")
                        .WithMany()
                        .HasForeignKey("CurrentClientProcessTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("ClientProcessDefinition");

                    b.Navigation("CurrentClientProcessStep");

                    b.Navigation("CurrentClientProcessTask");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessStep", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessDefinition", "ClientProcessDefinition")
                        .WithMany("Steps")
                        .HasForeignKey("ClientProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProcessDefinition");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessTask", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Client", "Client")
                        .WithMany("ProcessTasks")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessInstance", "ClientProcessInstance")
                        .WithMany("Tasks")
                        .HasForeignKey("ClientProcessInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessStep", "ClientProcessStep")
                        .WithMany("Tasks")
                        .HasForeignKey("ClientProcessStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("ClientProcessInstance");

                    b.Navigation("ClientProcessStep");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessTransition", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessStep", "ClientProcessStep")
                        .WithMany("OutgoingTransitions")
                        .HasForeignKey("ClientProcessStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessStep", "NextClientProcessStep")
                        .WithMany("IncomingTransitions")
                        .HasForeignKey("NextClientProcessStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClientProcessStep");

                    b.Navigation("NextClientProcessStep");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.Company", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Client", "Client")
                        .WithOne("Company")
                        .HasForeignKey("cCoder.ClientRelationshipManagement.Models.Entities.Company", "ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Address", "RegisteredAddress")
                        .WithMany("Companies")
                        .HasForeignKey("RegisteredAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("RegisteredAddress");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.Email", b =>
                {
                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.Client", "Client")
                        .WithMany("Emails")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientMaterial", "ClientMaterial")
                        .WithOne("Email")
                        .HasForeignKey("cCoder.ClientRelationshipManagement.Models.Entities.Email", "ClientMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("cCoder.ClientRelationshipManagement.Models.Entities.ClientContact", "SentToContact")
                        .WithMany("Emails")
                        .HasForeignKey("SentToContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("ClientMaterial");

                    b.Navigation("SentToContact");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.Address", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.Client", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Company");

                    b.Navigation("Contacts");

                    b.Navigation("Emails");

                    b.Navigation("HandoffPacks");

                    b.Navigation("Materials");

                    b.Navigation("Opportunities");

                    b.Navigation("ProcessInstances");

                    b.Navigation("ProcessTasks");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientContact", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Emails");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientMaterial", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientOpportunity", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("HandoffPacks");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessDefinition", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessInstance", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("cCoder.ClientRelationshipManagement.Models.Entities.ClientProcessStep", b =>
                {
                    b.Navigation("CurrentInstances");

                    b.Navigation("IncomingTransitions");

                    b.Navigation("OutgoingTransitions");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
