using cCoder.ClientRelationshipManagement.Models.Security;
using cCoder.ClientRelationshipManagement.Platform.Data;
using cCoder.ClientRelationshipManagement.Platform.Models.Entities;
using cCoder.Eventing;
using cCoder.Eventing.Models;
using Microsoft.EntityFrameworkCore;

namespace cCoder.ClientRelationshipManagement.Services.Entities;

public interface IProcessStepTaskStorageBroker { IQueryable<ProcessStepTask> SelectAll(); ValueTask<ProcessStepTask> InsertAsync(ProcessStepTask entity, CancellationToken token = default); ValueTask<ProcessStepTask> UpdateAsync(ProcessStepTask entity, CancellationToken token = default); ValueTask DeleteAsync(ProcessStepTask entity, CancellationToken token = default); }
internal sealed class ProcessStepTaskStorageBroker(ClientRelationshipDbContext context) : IProcessStepTaskStorageBroker
{
    public IQueryable<ProcessStepTask> SelectAll() => context.ProcessStepTasks;
    public async ValueTask<ProcessStepTask> InsertAsync(ProcessStepTask entity, CancellationToken token = default) { context.ProcessStepTasks.Add(entity); await context.SaveChangesAsync(token); return entity; }
    public async ValueTask<ProcessStepTask> UpdateAsync(ProcessStepTask entity, CancellationToken token = default) { ProcessStepTask local = context.ProcessStepTasks.Local.FirstOrDefault(x => x.Id == entity.Id); if (local is null) context.ProcessStepTasks.Update(entity); else context.Entry(local).CurrentValues.SetValues(entity); await context.SaveChangesAsync(token); return entity; }
    public async ValueTask DeleteAsync(ProcessStepTask entity, CancellationToken token = default) { context.ProcessStepTasks.Remove(entity); await context.SaveChangesAsync(token); }
}
public interface IProcessStepTaskFoundationService { IQueryable<ProcessStepTask> RetrieveAll(); IQueryable<ProcessStepTask> RetrieveWriteable(); ValueTask<ProcessStepTask> AddAsync(ProcessStepTask entity, CancellationToken token = default); ValueTask<ProcessStepTask> ModifyAsync(ProcessStepTask entity, CancellationToken token = default); ValueTask RemoveAsync(ProcessStepTask entity, CancellationToken token = default); }
internal sealed class ProcessStepTaskFoundationService(IProcessStepTaskStorageBroker broker, ICRMAuthInfo auth) : IProcessStepTaskFoundationService
{
    string[] Readable => auth.ReadableTenants?.Length > 0 ? auth.ReadableTenants : auth.WriteableTenants ?? [];
    string[] Writeable => auth.WriteableTenants ?? [];
    public IQueryable<ProcessStepTask> RetrieveAll() => broker.SelectAll().Where(x => Readable.Contains(x.ProcessStep.ProcessDefinition.TenantId));
    public IQueryable<ProcessStepTask> RetrieveWriteable() => broker.SelectAll().Where(x => Writeable.Contains(x.ProcessStep.ProcessDefinition.TenantId));
    public async ValueTask<ProcessStepTask> AddAsync(ProcessStepTask entity, CancellationToken token = default) { Ensure(); DateTimeOffset now = DateTimeOffset.UtcNow; ProcessStepTask copy = Copy(entity); copy.Id = copy.Id == Guid.Empty ? Guid.NewGuid() : copy.Id; copy.CreatedBy = copy.LastUpdatedBy = auth.SSOUserId; copy.CreatedOn = copy.LastUpdated = now; ProcessStepTask saved = await broker.InsertAsync(copy, token); CopyPersisted(saved, entity); return entity; }
    public async ValueTask<ProcessStepTask> ModifyAsync(ProcessStepTask entity, CancellationToken token = default) { Ensure(); ProcessStepTask old = await RetrieveWriteable().SingleOrDefaultAsync(x => x.Id == entity.Id, token) ?? throw new UnauthorizedAccessException(); ProcessStepTask copy = Copy(entity); copy.CreatedBy = old.CreatedBy; copy.CreatedOn = old.CreatedOn; copy.LastUpdatedBy = auth.SSOUserId; copy.LastUpdated = DateTimeOffset.UtcNow; ProcessStepTask saved = await broker.UpdateAsync(copy, token); CopyPersisted(saved, entity); return entity; }
    public async ValueTask RemoveAsync(ProcessStepTask entity, CancellationToken token = default) { ProcessStepTask old = await RetrieveWriteable().SingleOrDefaultAsync(x => x.Id == entity.Id, token) ?? throw new UnauthorizedAccessException(); await broker.DeleteAsync(old, token); }
    void Ensure() { if (string.IsNullOrWhiteSpace(auth.SSOUserId) || Writeable.Length == 0) throw new UnauthorizedAccessException(); }
    static ProcessStepTask Copy(ProcessStepTask x) => new() { Id=x.Id,CreatedBy=x.CreatedBy,LastUpdatedBy=x.LastUpdatedBy,CreatedOn=x.CreatedOn,LastUpdated=x.LastUpdated,ProcessStepId=x.ProcessStepId,Key=x.Key,Name=x.Name,Sequence=x.Sequence,Type=x.Type,HandlerKey=x.HandlerKey,InstructionsTemplate=x.InstructionsTemplate,RequiredContextKeys=x.RequiredContextKeys,ProducedContextKeys=x.ProducedContextKeys,MaxAttempts=x.MaxAttempts,IsActive=x.IsActive,NextTaskKey=x.NextTaskKey,FailureTaskKey=x.FailureTaskKey };
    static void CopyPersisted(ProcessStepTask x, ProcessStepTask y) { y.Id=x.Id;y.CreatedBy=x.CreatedBy;y.LastUpdatedBy=x.LastUpdatedBy;y.CreatedOn=x.CreatedOn;y.LastUpdated=x.LastUpdated;y.ProcessStepId=x.ProcessStepId;y.Key=x.Key;y.Name=x.Name;y.Sequence=x.Sequence;y.Type=x.Type;y.HandlerKey=x.HandlerKey;y.InstructionsTemplate=x.InstructionsTemplate;y.RequiredContextKeys=x.RequiredContextKeys;y.ProducedContextKeys=x.ProducedContextKeys;y.MaxAttempts=x.MaxAttempts;y.IsActive=x.IsActive;y.NextTaskKey=x.NextTaskKey;y.FailureTaskKey=x.FailureTaskKey; }
}
public interface IProcessStepTaskProcessingService : IProcessStepTaskFoundationService { }
internal sealed class ProcessStepTaskProcessingService(IProcessStepTaskFoundationService foundation) : IProcessStepTaskProcessingService { public IQueryable<ProcessStepTask> RetrieveAll()=>foundation.RetrieveAll(); public IQueryable<ProcessStepTask> RetrieveWriteable()=>foundation.RetrieveWriteable(); public ValueTask<ProcessStepTask> AddAsync(ProcessStepTask x,CancellationToken t=default)=>foundation.AddAsync(x,t); public ValueTask<ProcessStepTask> ModifyAsync(ProcessStepTask x,CancellationToken t=default)=>foundation.ModifyAsync(x,t); public ValueTask RemoveAsync(ProcessStepTask x,CancellationToken t=default)=>foundation.RemoveAsync(x,t); }
public interface IProcessStepTaskEventBroker { ValueTask RaiseAddAsync(EventMessage<ProcessStepTask> m); ValueTask RaiseUpdateAsync(EventMessage<ProcessStepTask> m); ValueTask RaiseDeleteAsync(EventMessage<ProcessStepTask> m); }
internal sealed class ProcessStepTaskEventBroker(IEventHub hub) : IProcessStepTaskEventBroker { public ValueTask RaiseAddAsync(EventMessage<ProcessStepTask> m)=>hub.RaiseEventAsync("process_step_task_add",m); public ValueTask RaiseUpdateAsync(EventMessage<ProcessStepTask> m)=>hub.RaiseEventAsync("process_step_task_update",m); public ValueTask RaiseDeleteAsync(EventMessage<ProcessStepTask> m)=>hub.RaiseEventAsync("process_step_task_delete",m); }
public interface IProcessStepTaskEventFoundationService { ValueTask RaiseAddAsync(ProcessStepTask x); ValueTask RaiseUpdateAsync(ProcessStepTask x); ValueTask RaiseDeleteAsync(ProcessStepTask x); }
internal sealed class ProcessStepTaskEventFoundationService(IProcessStepTaskEventBroker broker, ICRMAuthInfo auth) : IProcessStepTaskEventFoundationService { EventMessage<ProcessStepTask> M(ProcessStepTask x)=>new(){AuthInfo=new EventAuthInfo{SSOUserId=auth.SSOUserId},Data=x}; public ValueTask RaiseAddAsync(ProcessStepTask x)=>broker.RaiseAddAsync(M(x)); public ValueTask RaiseUpdateAsync(ProcessStepTask x)=>broker.RaiseUpdateAsync(M(x)); public ValueTask RaiseDeleteAsync(ProcessStepTask x)=>broker.RaiseDeleteAsync(M(x)); }
public interface IProcessStepTaskEventProcessingService : IProcessStepTaskEventFoundationService { }
internal sealed class ProcessStepTaskEventProcessingService(IProcessStepTaskEventFoundationService f) : IProcessStepTaskEventProcessingService { public ValueTask RaiseAddAsync(ProcessStepTask x)=>f.RaiseAddAsync(x); public ValueTask RaiseUpdateAsync(ProcessStepTask x)=>f.RaiseUpdateAsync(x); public ValueTask RaiseDeleteAsync(ProcessStepTask x)=>f.RaiseDeleteAsync(x); }
public interface IProcessStepTaskOrchestrationService { IQueryable<ProcessStepTask> RetrieveAll(); IQueryable<ProcessStepTask> RetrieveWriteable(); ValueTask<ProcessStepTask> AddAsync(ProcessStepTask x,CancellationToken t=default); ValueTask<ProcessStepTask> ModifyAsync(ProcessStepTask x,CancellationToken t=default); ValueTask RemoveAsync(ProcessStepTask x,CancellationToken t=default); }
internal sealed class ProcessStepTaskOrchestrationService(IProcessStepTaskProcessingService p,IProcessStepTaskEventProcessingService e) : IProcessStepTaskOrchestrationService { public IQueryable<ProcessStepTask> RetrieveAll()=>p.RetrieveAll(); public IQueryable<ProcessStepTask> RetrieveWriteable()=>p.RetrieveWriteable(); public async ValueTask<ProcessStepTask> AddAsync(ProcessStepTask x,CancellationToken t=default){var y=await p.AddAsync(x,t);await e.RaiseAddAsync(y);return y;} public async ValueTask<ProcessStepTask> ModifyAsync(ProcessStepTask x,CancellationToken t=default){var y=await p.ModifyAsync(x,t);await e.RaiseUpdateAsync(y);return y;} public async ValueTask RemoveAsync(ProcessStepTask x,CancellationToken t=default){await p.RemoveAsync(x,t);await e.RaiseDeleteAsync(x);} }
